"""schema initial

Revision ID: 603caf0cfe62
Revises: 
Create Date: 2026-09-14 16:35:26.287475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603caf0cfe62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
    sa.Column('id_parking', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_parking', sa.String(length=80), nullable=False),
    sa.Column('localisation_parking', sa.String(length=150), nullable=False),
    sa.Column('description_parking', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_parking')
    )
    op.create_table('role',
    sa.Column('code_role', sa.String(length=20), nullable=False),
    sa.Column('libelle_role', sa.String(length=50), nullable=False),
    sa.Column('description_role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code_role')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('prenom_utilisateur', sa.String(length=80), nullable=False),
    sa.Column('statut_compte', sa.String(length=20), nullable=False),
    sa.Column('besoin_pmr', sa.Boolean(), nullable=False),
    sa.Column('date_creation_compte', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attribution_role',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('code_role', sa.String(length=20), nullable=False),
    sa.Column('date_attribution', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['code_role'], ['role.code_role'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_utilisateur', 'code_role')
    )
    op.create_table('trace',
    sa.Column('id_trace', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('type_action', sa.String(length=50), nullable=False),
    sa.Column('entite_cible', sa.String(length=50), nullable=False),
    sa.Column('identifiant_cible', sa.Integer(), nullable=False),
    sa.Column('detail_action', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_trace')
    )
    op.create_table('zone',
    sa.Column('id_zone', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_parking', sa.Integer(), nullable=False),
    sa.Column('nom_zone', sa.String(length=80), nullable=False),
    sa.Column('capacite_theorique', sa.Integer(), nullable=False),
    sa.Column('heure_ouverture', sa.Time(), nullable=False),
    sa.Column('heure_fermeture', sa.Time(), nullable=False),
    sa.Column('zone_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_parking'], ['parking.id_parking'], ),
    sa.PrimaryKeyConstraint('id_zone')
    )
    op.create_table('blocage',
    sa.Column('id_blocage', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zone', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('motif_blocage', sa.String(length=255), nullable=False),
    sa.Column('date_debut_blocage', sa.DateTime(), nullable=False),
    sa.Column('date_fin_blocage', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_zone'], ['zone.id_zone'], ),
    sa.PrimaryKeyConstraint('id_blocage')
    )
    op.create_table('incident',
    sa.Column('id_incident', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zone', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur_signalement', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur_traitant', sa.Integer(), nullable=True),
    sa.Column('description_incident', sa.String(length=500), nullable=False),
    sa.Column('priorite_incident', sa.String(length=20), nullable=False),
    sa.Column('statut_incident', sa.String(length=20), nullable=False),
    sa.Column('date_signalement', sa.DateTime(), nullable=False),
    sa.Column('date_resolution', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur_signalement'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_utilisateur_traitant'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_zone'], ['zone.id_zone'], ),
    sa.PrimaryKeyConstraint('id_incident')
    )
    op.create_table('place',
    sa.Column('id_place', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zone', sa.Integer(), nullable=False),
    sa.Column('numero_place', sa.String(length=10), nullable=False),
    sa.Column('type_place', sa.String(length=20), nullable=False),
    sa.Column('etat_place', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_zone'], ['zone.id_zone'], ),
    sa.PrimaryKeyConstraint('id_place')
    )
    op.create_table('regle_acces',
    sa.Column('id_regle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_zone', sa.Integer(), nullable=False),
    sa.Column('libelle_regle', sa.String(length=100), nullable=False),
    sa.Column('niveau_priorite', sa.Integer(), nullable=False),
    sa.Column('date_debut_validite', sa.Date(), nullable=False),
    sa.Column('date_fin_validite', sa.Date(), nullable=True),
    sa.Column('regle_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_zone'], ['zone.id_zone'], ),
    sa.PrimaryKeyConstraint('id_regle')
    )
    op.create_table('cible_role',
    sa.Column('id_regle', sa.Integer(), nullable=False),
    sa.Column('code_role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['code_role'], ['role.code_role'], ),
    sa.ForeignKeyConstraint(['id_regle'], ['regle_acces.id_regle'], ),
    sa.PrimaryKeyConstraint('id_regle', 'code_role')
    )
    op.create_table('reservation',
    sa.Column('id_reservation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('statut_reservation', sa.String(length=20), nullable=False),
    sa.Column('date_creation_resa', sa.DateTime(), nullable=False),
    sa.Column('date_annulation', sa.DateTime(), nullable=True),
    sa.Column('motif_annulation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_reservation')
    )
    op.create_table('demande_visiteur',
    sa.Column('id_demande', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_demandeur', sa.Integer(), nullable=False),
    sa.Column('id_administrateur', sa.Integer(), nullable=True),
    sa.Column('id_reservation', sa.Integer(), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=False),
    sa.Column('date_visite_souhaitee', sa.DateTime(), nullable=False),
    sa.Column('motif_demande', sa.String(length=255), nullable=False),
    sa.Column('statut_demande', sa.String(length=20), nullable=False),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('commentaire_traitement', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_administrateur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_demandeur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservation.id_reservation'], ),
    sa.PrimaryKeyConstraint('id_demande'),
    sa.UniqueConstraint('id_reservation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demande_visiteur')
    op.drop_table('reservation')
    op.drop_table('cible_role')
    op.drop_table('regle_acces')
    op.drop_table('place')
    op.drop_table('incident')
    op.drop_table('blocage')
    op.drop_table('zone')
    op.drop_table('trace')
    op.drop_table('attribution_role')
    op.drop_table('utilisateur')
    op.drop_table('role')
    op.drop_table('parking')
    # ### end Alembic commands ###
